DELIMITER $$

CREATE DEFINER=`smartform_user`@`localhost` PROCEDURE `adv_my_daily_details_tb_UPDATE`()
BEGIN
	DROP TABLE IF EXISTS adv_my_daily_details_tb;
	CREATE TABLE adv_my_daily_details_tb as

    SELECT 
        amdr.race_id AS race_id,
        amdr.meeting_id AS meeting_id,
        amdr.meeting_date AS meeting_date,
        amdr.weather AS weather,
        amdr.meeting_status AS meeting_status,
        amdr.meeting_abandoned_reason AS meeting_abandoned_reason,
        amdr.draw_advantage AS draw_advantage,
        amdr.course AS course,
        amdr.country AS country,
        amdr.race_title AS race_title,
        amdr.race_type AS race_type,
        amdr.track_type AS track_type,
        amdr.direction AS direction,
        amdr.profile AS profile,
        amdr.general_features AS general_features,
        amdr.specific_features AS specific_features,
        amdr.advanced_going AS advanced_going,
        amdr.class AS class,
        amdr.handicap AS handicap,
        amdr.HCap AS HCap,
        amdr.trifecta AS trifecta,
        amdr.showcase AS showcase,
        amdr.age_range AS age_range,
        amdr.Distance AS Distance,
        amdr.distance_yards AS distance_yards,
        amdr.distance_furlongs AS distance_furlongs,
        amdr.added_money AS added_money,
        amdr.penalty_value AS penalty_value,
        amdr.scheduled_time AS scheduled_time,
        amdr.prize_pos_1 AS prize_pos_1,
        amdr.prize_pos_2 AS prize_pos_2,
        amdr.prize_pos_3 AS prize_pos_3,
        amdr.prize_pos_4 AS prize_pos_4,
        amdr.prize_pos_5 AS prize_pos_5,
        amdr.prize_pos_6 AS prize_pos_6,
        amdr.prize_pos_7 AS prize_pos_7,
        amdr.prize_pos_8 AS prize_pos_8,
        amdr.prize_pos_9 AS prize_pos_9,
        amdr.last_winner_no_race AS last_winner_no_race,
        amdr.last_winner_year AS last_winner_year,
        amdr.last_winner_runners AS last_winner_runners,
        amdr.last_winner_runner_id AS last_winner_runner_id,
        amdr.last_winner_name AS last_winner_name,
        amdr.last_winner_age AS last_winner_age,
        amdr.last_winner_bred AS last_winner_bred,
        amdr.last_winner_weight AS last_winner_weight,
        amdr.last_winner_trainer AS last_winner_trainer,
        amdr.last_winner_trainer_id AS last_winner_trainer_id,
        amdr.last_winner_jockey AS last_winner_jockey,
        amdr.last_winner_jockey_id AS last_winner_jockey_id,
        amdr.last_winner_sp AS last_winner_sp,
        amdr.last_winner_sp_decimal AS last_winner_sp_decimal,
        amdr.last_winner_betting_ranking AS last_winner_betting_ranking,
        amdr.last_winner_course_winner AS last_winner_course_winner,
        amdr.last_winner_distance_winner AS last_winner_distance_winner,
        amdr.last_winner_candd_winner AS last_winner_candd_winner,
        amdr.last_winner_beaten_favourite AS last_winner_beaten_favourite,
        adrunb.runner_id AS runner_id,
        adrunb.name AS name,
        adrunb.foaling_date AS foaling_date,
        adrunb.age AS age,
        adrunb.colour AS colour,
        adrunb.form_figures AS form_figures,
        adrunb.form_type AS form_type,
        adrunb.gender AS gender,
        adrunb.bred AS bred,
        adrunb.cloth_number AS cloth_number,
        adrunb.stall_number AS stall_number,
        adrunb.long_handicap AS long_handicap,
        adrunb.official_rating AS official_rating,
        adrunb.adjusted_rating AS adjusted_rating,
        adrunb.trainer_name AS trainer_name,
        adrunb.trainer_id AS trainer_id,
        adrunb.owner_name AS owner_name,
        adrunb.jockey_name AS jockey_name,
        adrunb.jockey_id AS jockey_id,
        adrunb.jockey_claim AS jockey_claim,
        adrunb.jockey_colours AS jockey_colours,
        adrunb.dam_name AS dam_name,
        adrunb.dam_year_born AS dam_year_born,
        adrunb.sire_name AS sire_name,
        adrunb.sire_year_born AS sire_year_born,
        adrunb.dam_sire_name AS dam_sire_name,
        adrunb.dam_sire_year_born AS dam_sire_year_born,
        adrunb.forecast_price AS forecast_price,
        adrunb.forecast_price_decimal AS forecast_price_decimal,
        adrunb.days_since_ran AS days_since_ran,
        adrunb.days_since_ran_flat AS days_since_ran_flat,
        adrunb.days_since_ran_jumps AS days_since_ran_jumps,
        adrunb.weight_pounds AS weight_pounds,
        adrunb.weight_penalty AS weight_penalty,
        adrunb.tack_hood AS tack_hood,
        adrunb.tack_visor AS tack_visor,
        adrunb.tack_blinkers AS tack_blinkers,
        adrunb.tack_eye_shield AS tack_eye_shield,
        adrunb.tack_eye_cover AS tack_eye_cover,
        adrunb.tack_cheek_piece AS tack_cheek_piece,
        adrunb.tack_pacifiers AS tack_pacifiers,
        adrunb.tack_tongue_strap AS tack_tongue_strap,
        adrunb.course_winner AS course_winner,
        adrunb.distance_winner AS distance_winner,
        adrunb.candd_winner AS candd_winner,
        adrunb.beaten_favourite AS beaten_favourite,
        IF((nr.runner_id IS NOT NULL),
            NULL,
            1) AS Running_bool
    FROM
        ((adv_my_daily_races amdr
        JOIN advance_daily_runners_beta adrunb ON ((amdr.race_id = adrunb.race_id)))
        LEFT JOIN non_runners nr ON (((amdr.race_id = nr.race_id)
            AND (adrunb.runner_id = nr.runner_id))))
    ORDER BY amdr.scheduled_time , adrunb.cloth_number;
END$$

DELIMITER ;