DELIMITER $$
-- Chefs-de-Race lookup (Bloodhorse Oct 2019 alphabetical roster + later international additions).
-- Fields: Sire_Name, Aptitudinal_Group_1 (B/I/C/S/P), Aptitudinal_Group_2 (B/I/C/S/P or NULL).
CREATE PROCEDURE `chefs_de_race_UPDATE`()
BEGIN
    CREATE TABLE IF NOT EXISTS `chefs_de_race` (
        `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
        `Sire_Name` VARCHAR(128) NOT NULL,
        `Aptitudinal_Group_1` ENUM('B','I','C','S','P') NOT NULL,
        `Aptitudinal_Group_2` ENUM('B','I','C','S','P') NULL DEFAULT NULL,
        `name_key` VARCHAR(128) NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `uq_chefs_name_key` (`name_key`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

    INSERT IGNORE INTO `chefs_de_race` (`Sire_Name`, `Aptitudinal_Group_1`, `Aptitudinal_Group_2`, `name_key`) VALUES
('Abernant', 'B', NULL, 'abernant'),
('Ack Ack', 'I', 'C', 'ack ack'),
('Admiral Drake', 'P', NULL, 'admiral drake'),
('Alcantara II', 'P', NULL, 'alcantara ii'),
('Alibhai', 'C', NULL, 'alibhai'),
('Alizier', 'P', NULL, 'alizier'),
('Alycidon', 'P', NULL, 'alycidon'),
('Alydar', 'C', NULL, 'alydar'),
('Apalachee', 'B', NULL, 'apalachee'),
('A.P. Indy', 'I', 'C', 'a.p. indy'),
('Asterus', 'S', NULL, 'asterus'),
('Aureole', 'C', NULL, 'aureole'),
('Awesome Again', 'I', 'C', 'awesome again'),
('Bachelor''s Double', 'S', NULL, 'bachelor''s double'),
('Bahram', 'C', NULL, 'bahram'),
('Baldski', 'B', 'I', 'baldski'),
('Ballymoss', 'S', NULL, 'ballymoss'),
('Bayardo', 'P', NULL, 'bayardo'),
('Ben Brush', 'I', NULL, 'ben brush'),
('Best Turn', 'C', NULL, 'best turn'),
('Big Game', 'I', NULL, 'big game'),
('Black Toney', 'B', 'I', 'black toney'),
('Blandford', 'C', NULL, 'blandford'),
('Blenheim II', 'C', 'S', 'blenheim ii'),
('Blue Larkspur', 'C', NULL, 'blue larkspur'),
('Blushing Groom', 'B', 'C', 'blushing groom'),
('Bois Roussel', 'S', NULL, 'bois roussel'),
('Bold Bidder', 'I', 'C', 'bold bidder'),
('Bold Ruckus', 'I', 'C', 'bold ruckus'),
('Bold Ruler', 'B', 'I', 'bold ruler'),
('Brantome', 'C', NULL, 'brantome'),
('British Empire', 'B', NULL, 'british empire'),
('Broad Brush', 'I', 'C', 'broad brush'),
('Broomstick', 'I', NULL, 'broomstick'),
('Bruleur', 'P', NULL, 'bruleur'),
('Buckaroo', 'B', 'I', 'buckaroo'),
('Buckpasser', 'C', NULL, 'buckpasser'),
('Bull Dog', 'B', NULL, 'bull dog'),
('Bull Lea', 'C', NULL, 'bull lea'),
('Busted', 'S', NULL, 'busted'),
('Cape Cross', 'C', NULL, 'cape cross'),
('Caro', 'I', 'C', 'caro'),
('Carson City', 'B', 'I', 'carson city'),
('Chateau Bouscaut', 'P', NULL, 'chateau bouscaut'),
('Chaucer', 'S', NULL, 'chaucer'),
('Chief''s Crown', 'I', 'S', 'chief''s crown'),
('Cicero', 'B', NULL, 'cicero'),
('Clarissimus', 'C', NULL, 'clarissimus'),
('Codex', 'I', 'C', 'codex'),
('Colorado', 'I', NULL, 'colorado'),
('Congreve', 'I', NULL, 'congreve'),
('Count Fleet', 'C', NULL, 'count fleet'),
('Court Martial', 'B', NULL, 'court martial'),
('Creme Dela Creme', 'C', 'S', 'creme dela creme'),
('Crepello', 'P', NULL, 'crepello'),
('Damascus', 'I', 'C', 'damascus'),
('Danzig', 'I', 'C', 'danzig'),
('Dark Ronald', 'P', NULL, 'dark ronald'),
('Darshaan', 'S', NULL, 'darshaan'),
('Discovery', 'S', NULL, 'discovery'),
('Djebel', 'I', NULL, 'djebel'),
('Donatello II', 'P', NULL, 'donatello ii'),
('Double Jay', 'B', NULL, 'double jay'),
('Dr. Fager', 'I', NULL, 'dr. fager'),
('Dubawi', 'I', 'S', 'dubawi'),
('Eight Thirty', 'I', NULL, 'eight thirty'),
('El Prado', 'B', 'I', 'el prado'),
('Ela-Mana-Mou', 'P', NULL, 'ela-mana-mou'),
('Equipoise', 'I', 'C', 'equipoise'),
('Exclusive Native', 'C', NULL, 'exclusive native'),
('Fair Play', 'S', 'P', 'fair play'),
('Fair Trial', 'B', NULL, 'fair trial'),
('Fairway', 'B', NULL, 'fairway'),
('Fappiano', 'I', 'C', 'fappiano'),
('Fasliyev', 'B', NULL, 'fasliyev'),
('Forli', 'C', NULL, 'forli'),
('Foxbridge', 'P', NULL, 'foxbridge'),
('Full Sail', 'I', NULL, 'full sail'),
('Gainsborough', 'C', NULL, 'gainsborough'),
('Galileo', 'C', 'S', 'galileo'),
('Gallant Man', 'B', 'I', 'gallant man'),
('Giant''s Causeway', 'C', NULL, 'giant''s causeway'),
('Gone West', 'I', 'C', 'gone west'),
('Graustark', 'C', 'S', 'graustark'),
('Grey Dawn II', 'B', 'I', 'grey dawn ii'),
('Grey Sovereign', 'B', NULL, 'grey sovereign'),
('Gundomar', 'C', NULL, 'gundomar'),
('Habitat', 'B', NULL, 'habitat'),
('Hail to Reason', 'C', NULL, 'hail to reason'),
('Halo', 'B', 'C', 'halo'),
('Havresac II', 'I', NULL, 'havresac ii'),
('Heliopolis', 'B', NULL, 'heliopolis'),
('Herbager', 'C', 'S', 'herbager'),
('High Top', 'C', NULL, 'high top'),
('His Majesty', 'C', NULL, 'his majesty'),
('Hoist the Flag', 'B', 'I', 'hoist the flag'),
('Hurry On', 'P', NULL, 'hurry on'),
('Hyperion', 'B', 'C', 'hyperion'),
('Icecapade', 'B', 'C', 'icecapade'),
('In Reality', 'B', 'C', 'in reality'),
('In the Wings', 'C', 'S', 'in the wings'),
('Indian Ridge', 'I', NULL, 'indian ridge'),
('Intentionally', 'B', 'I', 'intentionally'),
('Key to the Mint', 'B', 'C', 'key to the mint'),
('Khaled', 'I', NULL, 'khaled'),
('King Salmon', 'I', NULL, 'king salmon'),
('Kingmambo', 'C', 'S', 'kingmambo'),
('King''s Bishop', 'B', 'I', 'king''s bishop'),
('La Farina', 'P', NULL, 'la farina'),
('Le Fabuleux', 'P', NULL, 'le fabuleux'),
('Linamix', 'C', 'S', 'linamix'),
('Lost Code', 'B', 'I', 'lost code'),
('Luthier', 'C', NULL, 'luthier'),
('Lyphard', 'C', NULL, 'lyphard'),
('Mahmoud', 'I', 'C', 'mahmoud'),
('Man o'' War', 'S', NULL, 'man o'' war'),
('Massine', 'P', NULL, 'massine'),
('Midstream', 'C', NULL, 'midstream'),
('Mieuxce', 'P', NULL, 'mieuxce'),
('Mill Reef', 'C', 'S', 'mill reef'),
('Monsun', 'C', 'S', 'monsun'),
('Montjeu', 'C', 'S', 'montjeu'),
('Mossborough', 'C', NULL, 'mossborough'),
('Mr. Prospector', 'B', 'C', 'mr. prospector'),
('My Babu', 'B', NULL, 'my babu'),
('Nashua', 'I', 'C', 'nashua'),
('Nasrullah', 'B', NULL, 'nasrullah'),
('Native Dancer', 'I', 'C', 'native dancer'),
('Navarro', 'C', NULL, 'navarro'),
('Nearco', 'B', 'C', 'nearco'),
('Never Bend', 'B', 'I', 'never bend'),
('Never Say Die', 'C', NULL, 'never say die'),
('Nijinsky II', 'C', 'S', 'nijinsky ii'),
('Niniski', 'C', 'P', 'niniski'),
('Nodouble', 'C', 'P', 'nodouble'),
('Noholme II', 'B', 'C', 'noholme ii'),
('Northern Dancer', 'B', 'C', 'northern dancer'),
('Nureyev', 'C', NULL, 'nureyev'),
('Oleander', 'S', NULL, 'oleander'),
('Olympia', 'B', NULL, 'olympia'),
('Orby', 'B', NULL, 'orby'),
('Ortello', 'P', NULL, 'ortello'),
('Panorama', 'B', NULL, 'panorama'),
('Persian Gulf', 'C', NULL, 'persian gulf'),
('Peter Pan', 'B', NULL, 'peter pan'),
('Petition', 'I', NULL, 'petition'),
('Phalaris', 'B', NULL, 'phalaris'),
('Pharis II', 'B', NULL, 'pharis ii'),
('Pharos', 'I', NULL, 'pharos'),
('Pia Star', 'S', NULL, 'pia star'),
('Pilate', 'C', NULL, 'pilate'),
('Pivotal', 'I', 'C', 'pivotal'),
('Pleasant Colony', 'I', NULL, 'pleasant colony'),
('Polynesian', 'I', NULL, 'polynesian'),
('Pompey', 'B', NULL, 'pompey'),
('Precipitation', 'P', NULL, 'precipitation'),
('Pretense', 'C', NULL, 'pretense'),
('Prince Bio', 'C', NULL, 'prince bio'),
('Prince Chevalier', 'C', NULL, 'prince chevalier'),
('Prince John', 'C', NULL, 'prince john'),
('Prince Rose', 'C', NULL, 'prince rose'),
('Princequillo', 'I', 'S', 'princequillo'),
('Promised Land', 'C', NULL, 'promised land'),
('Pulpit', 'I', 'C', 'pulpit'),
('Rabelais', 'P', NULL, 'rabelais'),
('Rainbow Quest', 'C', 'S', 'rainbow quest'),
('Raise a Native', 'B', NULL, 'raise a native'),
('Reliance II', 'S', 'P', 'reliance ii'),
('Relko', 'S', NULL, 'relko'),
('Reviewer', 'B', 'C', 'reviewer'),
('Ribot', 'C', 'P', 'ribot'),
('Right Royal', 'S', NULL, 'right royal'),
('Riverman', 'I', 'C', 'riverman'),
('Roberto', 'C', NULL, 'roberto'),
('Rock Sand', 'C', 'S', 'rock sand'),
('Roman', 'B', 'I', 'roman'),
('Rough''n Tumble', 'B', 'C', 'rough''n tumble'),
('Round Table', 'S', NULL, 'round table'),
('Royal Academy', 'B', 'I', 'royal academy'),
('Royal Charger', 'B', NULL, 'royal charger'),
('Run the Gantlet', 'P', NULL, 'run the gantlet'),
('Sadler''s Wells', 'C', 'S', 'sadler''s wells'),
('Sardanapale', 'P', NULL, 'sardanapale'),
('Sea-Bird', 'S', NULL, 'sea-bird'),
('Seattle Slew', 'B', 'C', 'seattle slew'),
('Secretariat', 'I', 'C', 'secretariat'),
('Shamardal', 'I', 'C', 'shamardal'),
('Sharpen Up', 'B', 'C', 'sharpen up'),
('Shirley Heights', 'C', 'P', 'shirley heights'),
('Sicambre', 'C', NULL, 'sicambre'),
('Sideral', 'C', NULL, 'sideral'),
('Sir Cosmo', 'B', NULL, 'sir cosmo'),
('Sir Gallahad III', 'C', NULL, 'sir gallahad iii'),
('Sir Gaylord', 'I', 'C', 'sir gaylord'),
('Sir Ivor', 'I', 'C', 'sir ivor'),
('Smart Strike', 'I', 'C', 'smart strike'),
('Solario', 'P', NULL, 'solario'),
('Son-in-Law', 'P', NULL, 'son-in-law'),
('Speak John', 'B', 'I', 'speak john'),
('Spearmint', 'P', NULL, 'spearmint'),
('Spy Song', 'B', NULL, 'spy song'),
('Stage Door Johnny', 'S', 'P', 'stage door johnny'),
('Star Kingdom', 'I', 'C', 'star kingdom'),
('Star Shoot', 'I', NULL, 'star shoot'),
('Sunny Boy', 'P', NULL, 'sunny boy'),
('Sunstar', 'S', NULL, 'sunstar'),
('Sweep', 'I', NULL, 'sweep'),
('Swynford', 'C', NULL, 'swynford'),
('T.V. Lark', 'I', NULL, 't.v. lark'),
('Tantieme', 'S', NULL, 'tantieme'),
('Teddy', 'S', NULL, 'teddy'),
('The Tetrarch', 'I', NULL, 'the tetrarch'),
('Ticino', 'C', 'S', 'ticino'),
('Tom Fool', 'I', 'C', 'tom fool'),
('Tom Rolfe', 'C', 'P', 'tom rolfe'),
('Tourbillon', 'C', 'P', 'tourbillon'),
('Tracery', 'C', NULL, 'tracery'),
('Traghetto', 'I', NULL, 'traghetto'),
('Tudor Minstrel', 'B', NULL, 'tudor minstrel'),
('Turn-to', 'B', 'I', 'turn-to'),
('Ultimus', 'B', NULL, 'ultimus'),
('Unbridled', 'B', 'I', 'unbridled'),
('Unbridled''s Song', 'B', 'C', 'unbridled''s song'),
('Vaguely Noble', 'C', 'P', 'vaguely noble'),
('Vandale', 'P', NULL, 'vandale'),
('Vatellor', 'P', NULL, 'vatellor'),
('Vatout', 'S', NULL, 'vatout'),
('Vieux Manoir', 'C', NULL, 'vieux manoir'),
('War Admiral', 'C', NULL, 'war admiral'),
('What a Pleasure', 'B', NULL, 'what a pleasure'),
('Wild Risk', 'P', NULL, 'wild risk'),
('Worden', 'S', NULL, 'worden'),
('Alleged', 'C', 'P', 'alleged'),
('Arch', 'C', NULL, 'arch'),
('Bolt d''Oro', 'B', 'C', 'bolt d''oro'),
('Candy Ride', 'B', 'C', 'candy ride'),
('Constitution', 'B', 'C', 'constitution'),
('Cozzene', 'C', 'S', 'cozzene'),
('Curlin', 'C', NULL, 'curlin'),
('Distorted Humor', 'I', 'C', 'distorted humor'),
('Dynaformer', 'C', NULL, 'dynaformer'),
('Elusive Quality', 'B', 'C', 'elusive quality'),
('Empire Maker', 'C', 'S', 'empire maker'),
('English Channel', 'S', 'P', 'english channel'),
('Forestry', 'B', 'I', 'forestry'),
('Great Above', 'B', 'C', 'great above'),
('Gun Runner', 'B', 'C', 'gun runner'),
('Holy Bull', 'I', 'C', 'holy bull'),
('In Excess', 'B', 'I', 'in excess'),
('Into Mischief', 'B', 'C', 'into mischief'),
('Kantharos', 'B', 'I', 'kantharos'),
('Kitten''s Joy', 'C', NULL, 'kitten''s joy'),
('Liam''s Map', 'C', NULL, 'liam''s map'),
('Lord Avie', 'C', NULL, 'lord avie'),
('Maclean''s Music', 'B', NULL, 'maclean''s music'),
('Medaglia d''Oro', 'C', NULL, 'medaglia d''oro'),
('More Than Ready', 'B', 'C', 'more than ready'),
('Munnings', 'B', 'I', 'munnings'),
('Not This Time', 'B', 'C', 'not this time'),
('Practical Joke', 'B', 'I', 'practical joke'),
('Quality Road', 'I', 'C', 'quality road'),
('Quiet American', 'C', NULL, 'quiet american'),
('Rubiano', 'B', 'I', 'rubiano'),
('Scat Daddy', 'I', 'C', 'scat daddy'),
('Slewpy', 'B', 'I', 'slewpy'),
('Speightstown', 'B', 'I', 'speightstown'),
('Street Cry', 'I', 'C', 'street cry'),
('Street Sense', 'B', 'C', 'street sense'),
('Tapit', 'C', NULL, 'tapit'),
('Thunder Gulch', 'C', NULL, 'thunder gulch'),
('Tiznow', 'I', 'C', 'tiznow'),
('Twirling Candy', 'B', 'I', 'twirling candy'),
('Uncle Mo', 'I', 'C', 'uncle mo'),
('Violence', 'B', NULL, 'violence');
END $$
DELIMITER ;
