CREATE DEFINER=`smartform`@`localhost` PROCEDURE `my_daily_details_tb_UPDATE`()
BEGIN

	DROP TABLE IF EXISTS my_daily_details_tb;
	CREATE TABLE my_daily_details_tb as

	SELECT 
        mdr.race_id AS race_id,
        mdr.meeting_id AS meeting_id,
        mdr.meeting_date AS meeting_date,
        mdr.weather AS weather,
        mdr.meeting_status AS meeting_status,
        mdr.meeting_abandoned_reason AS meeting_abandoned_reason,
        mdr.draw_advantage AS draw_advantage,
        mdr.course AS course,
        mdr.country AS country,
        mdr.race_title AS race_title,
        mdr.race_type AS race_type,
        mdr.track_type AS track_type,
        mdr.direction AS direction,
        mdr.profile AS profile,
        mdr.general_features AS general_features,
        mdr.specific_features AS specific_features,
        mdr.advanced_going AS advanced_going,
        mdr.class AS class,
        mdr.handicap AS handicap,
        mdr.HCap AS HCap,
        mdr.trifecta AS trifecta,
        mdr.showcase AS showcase,
        mdr.age_range AS age_range,
        mdr.Distance AS Distance,
        mdr.distance_yards AS distance_yards,
        mdr.distance_furlongs AS distance_furlongs,
        mdr.added_money AS added_money,
        mdr.penalty_value AS penalty_value,
        mdr.scheduled_time AS scheduled_time,
        mdr.prize_pos_1 AS prize_pos_1,
        mdr.prize_pos_2 AS prize_pos_2,
        mdr.prize_pos_3 AS prize_pos_3,
        mdr.prize_pos_4 AS prize_pos_4,
        mdr.prize_pos_5 AS prize_pos_5,
        mdr.prize_pos_6 AS prize_pos_6,
        mdr.prize_pos_7 AS prize_pos_7,
        mdr.prize_pos_8 AS prize_pos_8,
        mdr.prize_pos_9 AS prize_pos_9,
        mdr.last_winner_no_race AS last_winner_no_race,
        mdr.last_winner_year AS last_winner_year,
        mdr.last_winner_runners AS last_winner_runners,
        mdr.last_winner_runner_id AS last_winner_runner_id,
        mdr.last_winner_name AS last_winner_name,
        mdr.last_winner_age AS last_winner_age,
        mdr.last_winner_bred AS last_winner_bred,
        mdr.last_winner_weight AS last_winner_weight,
        mdr.last_winner_trainer AS last_winner_trainer,
        mdr.last_winner_trainer_id AS last_winner_trainer_id,
        mdr.last_winner_jockey AS last_winner_jockey,
        mdr.last_winner_jockey_id AS last_winner_jockey_id,
        mdr.last_winner_sp AS last_winner_sp,
        mdr.last_winner_sp_decimal AS last_winner_sp_decimal,
        mdr.last_winner_betting_ranking AS last_winner_betting_ranking,
        mdr.last_winner_course_winner AS last_winner_course_winner,
        mdr.last_winner_distance_winner AS last_winner_distance_winner,
        mdr.last_winner_candd_winner AS last_winner_candd_winner,
        mdr.last_winner_beaten_favourite AS last_winner_beaten_favourite,
        drunb.runner_id AS runner_id,
        drunb.name AS name,
        drunb.foaling_date AS foaling_date,
        drunb.age AS age,
        drunb.colour AS colour,
        drunb.form_figures AS form_figures,
        drunb.form_type AS form_type,
        drunb.gender AS gender,
        drunb.bred AS bred,
        drunb.cloth_number AS cloth_number,
        drunb.stall_number AS stall_number,
        drunb.long_handicap AS long_handicap,
        drunb.official_rating AS official_rating,
        drunb.adjusted_rating AS adjusted_rating,
        drunb.trainer_name AS trainer_name,
        drunb.trainer_id AS trainer_id,
        drunb.owner_name AS owner_name,
        drunb.jockey_name AS jockey_name,
        drunb.jockey_id AS jockey_id,
        drunb.jockey_claim AS jockey_claim,
        drunb.jockey_colours AS jockey_colours,
        drunb.dam_name AS dam_name,
        drunb.dam_year_born AS dam_year_born,
        drunb.sire_name AS sire_name,
        drunb.sire_year_born AS sire_year_born,
        drunb.dam_sire_name AS dam_sire_name,
        drunb.dam_sire_year_born AS dam_sire_year_born,
        drunb.forecast_price AS forecast_price,
        drunb.forecast_price_decimal AS forecast_price_decimal,
        drunb.days_since_ran AS days_since_ran,
        drunb.days_since_ran_flat AS days_since_ran_flat,
        drunb.days_since_ran_jumps AS days_since_ran_jumps,
        drunb.weight_pounds AS weight_pounds,
        drunb.weight_penalty AS weight_penalty,
        drunb.tack_hood AS tack_hood,
        drunb.tack_visor AS tack_visor,
        drunb.tack_blinkers AS tack_blinkers,
        drunb.tack_eye_shield AS tack_eye_shield,
        drunb.tack_eye_cover AS tack_eye_cover,
        drunb.tack_cheek_piece AS tack_cheek_piece,
        drunb.tack_pacifiers AS tack_pacifiers,
        drunb.tack_tongue_strap AS tack_tongue_strap,
        drunb.course_winner AS course_winner,
        drunb.distance_winner AS distance_winner,
        drunb.candd_winner AS candd_winner,
        drunb.beaten_favourite AS beaten_favourite,
        IF((nr.runner_id IS NOT NULL),
            NULL,
            1) AS Running_bool
    FROM
        ((my_daily_races mdr
        JOIN daily_runners_beta drunb ON ((mdr.race_id = drunb.race_id)))
        LEFT JOIN non_runners nr ON (((mdr.race_id = nr.race_id)
            AND (drunb.runner_id = nr.runner_id))))
    ORDER BY mdr.scheduled_time , drunb.cloth_number;
END