DELIMITER $$
CREATE PROCEDURE `speed&performance_table_UPDATE`()
BEGIN
	DROP TABLE IF EXISTS `speed&performance_table`;
    CREATE TABLE `speed&performance_table` AS
	SELECT 
		`drc`.`PK` AS `PK`,
		`drc`.`race_id` AS `race_id`,
		`drc`.`runner_id` AS `runner_id`,
		`drc`.`Date` AS `Date`,
		`drc`.`Time` AS `Time`,
		`drc`.`course` AS `course`,
		`drc`.`Distance` AS `Distance`,
		`dracb`.`distance_yards` AS `distance_yards`,
		`dri`.`prev_runner_win_strike` AS `prev_runner_win_strike`,
		`dri`.`prev_runner_place_strike` AS `prev_runner_place_strike`,
		`dri`.`going_prev_win_strike` AS `going_prev_win_strike`,
		`dri`.`going_prev_place_strike` AS `going_prev_place_strike`,
		`dri`.`distance_prev_win_strike` AS `distance_prev_win_strike`,
		`dri`.`distance_prev_place_strike` AS `distance_prev_place_strike`,
		`dri`.`course_prev_win_strike` AS `course_prev_win_strike`,
		`dri`.`course_prev_place_strike` AS `course_prev_place_strike`,
		`dri`.`class_prev_win_strike` AS `class_prev_win_strike`,
		`dri`.`class_prev_place_strike` AS `class_prev_place_strike`,
		`dri`.`direction_prev_runs` AS `direction_prev_runs`,
		`dri`.`direction_prev_place_strike` AS `direction_prev_place_strike`,
		`dri`.`direction_prev_win_strike` AS `direction_prev_win_strike`,
		`dri`.`all_prev_useful_runs_strike` AS `all_prev_useful_runs_strike`,
		`dri`.`speed_rating_LTO_in_race` AS `Betwise_speed_rating_LTO_in_race`,
		`dri`.`speed_rating_LTO` AS `Betwise_speed_rating_LTO`,
		`dri`.`speed_rating_PTO` AS `Betwise_speed_rating_PTO`,
		`dri`.`speed_rating_ATO` AS `Betwise_speed_rating_ATO`,
		`drc`.`Furlongs` AS `Furlongs`,
		`drc`.`cloth_number` AS `cloth_number`,
		`drc`.`stall_number` AS `stall_number`,
		ROUND(`db`.`win_percent_by_stall`, 2) AS `draw_bias_pct`,
		`db`.`n` AS `draw_bias_reliability_~150`,
		`drunb`.`form_figures` AS `form_figures`,
		`drunb`.`days_since_ran` AS `days_since_ran`,
		`drunb`.`weight_pounds` AS `weight_pounds`,
		`drunb`.`foaling_date` AS `foaling_date`,
		`drunb`.`colour` AS `colour`,
		`drunb`.`gender` AS `gender`,
		`drunb`.`age` AS `age`,
		`drunb`.`bred` AS `bred`,
		`drunb`.`owner_name` AS `owner_name`,
		`drunb`.`dam_name` AS `dam_name`,
		`ar`.`dam_origin` AS `dam_origin`,
		`drunb`.`sire_name` AS `sire_name`,
		`ar`.`sire_origin` AS `sire_origin`,
		`drunb`.`course_winner` AS `course_winner`,
		`drunb`.`distance_winner` AS `distance_winner`,
		`dri`.`going_prev_wins` AS `going_prev_wins`,
		`drunb`.`candd_winner` AS `candd_winner`,
		`drunb`.`beaten_favourite` AS `beaten_favourite`,
		`drc`.`name` AS `name`,
		`dri`.`class_diff` AS `class_diff`,
		`dri`.`distance_diff` AS `distance_diff`,
		`dri`.`official_rating_diff` AS `official_rating_diff`,
		`drc`.`jockey_name` AS `jockey_name`,
		`drunb`.`jockey_claim` AS `jockey_claim`,
		`drc`.`trainer_name` AS `trainer_name`,
		`drunb`.`official_rating` AS `official_rating`,
		`drc`.`forecast_price` AS `forecast_price`,
		`drc`.`forecast_price_decimal` AS `forecast_price_decimal`,
		`drc`.`TnrRuns14d` AS `TnrRuns14d`,
		`drc`.`TnrWins14d` AS `TnrWins14d`,
		`drc`.`TnrPlaced14d` AS `TnrPlaced14d`,
		`drc`.`TnrWinPct14d` AS `TnrWinPct14d`,
		`drc`.`TnrRTPPct14d` AS `TnrRTPPct14d`,
		`drc`.`TnrWinProfit14d` AS `TnrWinProfit14d`,
		`drc`.`JkyRuns14d` AS `JkyRuns14d`,
		`drc`.`JkyWins14d` AS `JkyWins14d`,
		`drc`.`JkyPlaced14d` AS `JkyPlaced14d`,
		`drc`.`JkyWinPct14d` AS `JkyWinPct14d`,
		`drc`.`JkyPlcPct14d` AS `JkyPlcPct14d`,
		`drc`.`JkyWinProfit14d` AS `JkyWinProfit14d`,
		`drc`.`TnrJkyPlacePct` AS `TnrJkyPlacePct`,
		`dcr`.`comment_rating` AS `fhorsite_rating`,
		`dcr`.`comment_reliability_factor` AS `fhorsite_rating_reliability`,
		`sa`.`meeting_date_LTO` AS `meeting_date_LTO`,
		`sa`.`wt_speed_rating_LTO` AS `wt_speed_rating_LTO`,
		`sa`.`speed_rating_LTO` AS `SR_LTO`,
		`sa`.`SR_2` AS `SR_2`,
		`sa`.`SR_3` AS `SR_3`,
		`sa`.`SR_4` AS `SR_4`,
		`sa`.`SR_5` AS `SR_5`,
		`sa`.`SR_6` AS `SR_6`,
		`sa`.`class_LTO` AS `class_LTO`,
		`sa`.`CL_2` AS `CL_2`,
		`sa`.`CL_3` AS `CL_3`,
		`sa`.`CL_4` AS `CL_4`,
		`sa`.`CL_5` AS `CL_5`,
		`sa`.`CL_6` AS `CL_6`,
		`sa`.`distance_furlongs_LTO` AS `distance_furlongs_LTO`,
		`sa`.`DF_2` AS `DF_2`,
		`sa`.`DF_3` AS `DF_3`,
		`sa`.`DF_4` AS `DF_4`,
		`sa`.`DF_5` AS `DF_5`,
		`sa`.`DF_6` AS `DF_6`,
		`sa`.`going_LTO` AS `going_LTO`,
		`sa`.`going_1` AS `going_1`,
		`sa`.`going_2` AS `going_2`,
		`sa`.`going_3` AS `going_3`,
		`sa`.`going_4` AS `going_4`,
		`sa`.`going_5` AS `going_5`,
		`sa`.`going_6` AS `going_6`,
		`dracb`.`race_title` AS `race_title`,
		`dracb`.`weather` AS `weather`,
		`dracb`.`draw_advantage` AS `draw_advantage`,
		`dracb`.`race_type` AS `race_type`,
		`dracb`.`track_type` AS `track_type`,
		`dracb`.`advanced_going` AS `advanced_going`,
		`dracb`.`class` AS `class`,
		IF((`dracb`.`handicap` = 1),
			'Handicap',
			'Non-Handicap') AS `handicap`,
		`dracb`.`age_range` AS `age_range`,
		`dracb`.`prize_pos_1` AS `prize_pos_1`,
		`dracb`.`last_winner_year` AS `last_winner_year`,
		`dracb`.`last_winner_runners` AS `last_winner_runners`,
		`dracb`.`last_winner_name` AS `last_winner_name`,
		`dracb`.`last_winner_age` AS `last_winner_age`,
		`dracb`.`last_winner_bred` AS `last_winner_bred`,
		`dracb`.`last_winner_weight` AS `last_winner_weight`,
		`dracb`.`last_winner_trainer` AS `last_winner_trainer`,
		`dracb`.`last_winner_jockey` AS `last_winner_jockey`,
        `dti`.`rc_21D_prb` AS `trn_rc_21D_prb`,
        `dti`.`rc_42D_prb` AS `trn_rc_42D_prb`,
        `dti`.`rc_5Y_prb` AS `trn_rc_5Y_prb`,
        `dji`.`rc_21D_prb` AS `jky_rc_21D_prb`,
        `dji`.`rc_42D_prb` AS `jky_rc_42D_prb`,
        `dji`.`rc_5Y_prb` AS `jky_rc_5Y_prb`
	FROM `dailyracecard14` `drc`
		LEFT JOIN `speed_analysis` `sa` ON (`drc`.`runner_id` = `sa`.`runner_id`)
		LEFT JOIN `daily_races_beta` `dracb` ON (`dracb`.`race_id` = `drc`.`race_id`)
		LEFT JOIN `daily_runners_beta` `drunb` ON ((`dracb`.`race_id` = `drunb`.`race_id`) AND (`drc`.`runner_id` = `drunb`.`runner_id`))
		LEFT JOIN `daily_comment_ratings` `dcr` ON (`drc`.`runner_id` = `dcr`.`runner_id`)
		LEFT JOIN `daily_runners_insights` `dri` ON ((`dri`.`race_id` = `dracb`.`race_id`) AND (`dri`.`runner_id` = `drc`.`runner_id`))
		LEFT JOIN `draw_bias` `db` ON ((`drc`.`course` = `db`.`course`)
			AND (`dracb`.`race_type` = `db`.`race_type`)
			AND (`dracb`.`track_type` = `db`.`track_type`)
			AND (`drc`.`stall_number` = `db`.`stall_number`)
			AND (`dracb`.`distance_yards` <= `db`.`distance_yards_max`)
			AND (`dracb`.`distance_yards` >= `db`.`distance_yards_min`))
		LEFT JOIN `ancestry_records` `ar` ON (`drc`.`runner_id` = `ar`.`runner_id`)
        LEFT JOIN `daily_trainers_insights` `dti` ON ((`dti`.`race_id` = `drc`.`race_id`) AND (`dti`.`runner_id` = `drc`.`runner_id`))
        LEFT JOIN `daily_jockeys_insights` `dji` ON ((`dji`.`race_id` = `drc`.`race_id`) AND (`dji`.`runner_id` = `drc`.`runner_id`))
;
END $$
DELIMITER ;