<?php
/**
 * Chefs-de-Race catalog (Bloodhorse Oct 2019 roster + later international additions).
 *
 * Aptitudinal groups: B Brilliant, I Intermediate, C Classic, S Solid, P Professional.
 * Split chefs store both groups; generation points are halved between them.
 */

if (!defined('ABSPATH') && php_sapi_name() !== 'cli') {
    exit;
}

if (!function_exists('bricks_dosage_chefs_catalog')) {
    /**
     * @return array<int, array{0:string,1:string,2:?string}> [Sire_Name, Group1, Group2]
     */
    function bricks_dosage_chefs_catalog() {
        $raw = bricks_dosage_chefs_raw_map();
        $rows = [];
        foreach ($raw as $name => $groups) {
            $parts = explode('/', strtoupper(trim((string) $groups)));
            $g1 = isset($parts[0]) ? substr($parts[0], 0, 1) : '';
            $g2 = (isset($parts[1]) && $parts[1] !== '') ? substr($parts[1], 0, 1) : null;
            if (!in_array($g1, ['B', 'I', 'C', 'S', 'P'], true)) {
                continue;
            }
            if ($g2 !== null && !in_array($g2, ['B', 'I', 'C', 'S', 'P'], true)) {
                $g2 = null;
            }
            if ($g2 === $g1) {
                $g2 = null;
            }
            $rows[] = [$name, $g1, $g2];
        }
        return $rows;
    }
}

if (!function_exists('bricks_dosage_chefs_raw_map')) {
    /**
     * Canonical sire name => aptitudinal code (single or split).
     *
     * @return array<string, string>
     */
    function bricks_dosage_chefs_raw_map() {
        // Bloodhorse alphabetical Chefs-de-Race list (October 2019).
        $bloodhorse_2019 = [
            'Abernant' => 'B',
            'Ack Ack' => 'I/C',
            'Admiral Drake' => 'P',
            'Alcantara II' => 'P',
            'Alibhai' => 'C',
            'Alizier' => 'P',
            'Alycidon' => 'P',
            'Alydar' => 'C',
            'Apalachee' => 'B',
            'A.P. Indy' => 'I/C',
            'Asterus' => 'S',
            'Aureole' => 'C',
            'Awesome Again' => 'I/C',
            "Bachelor's Double" => 'S',
            'Bahram' => 'C',
            'Baldski' => 'B/I',
            'Ballymoss' => 'S',
            'Bayardo' => 'P',
            'Ben Brush' => 'I',
            'Best Turn' => 'C',
            'Big Game' => 'I',
            'Black Toney' => 'B/I',
            'Blandford' => 'C',
            'Blenheim II' => 'C/S',
            'Blue Larkspur' => 'C',
            'Blushing Groom' => 'B/C',
            'Bois Roussel' => 'S',
            'Bold Bidder' => 'I/C',
            'Bold Ruckus' => 'I/C',
            'Bold Ruler' => 'B/I',
            'Brantome' => 'C',
            'British Empire' => 'B',
            'Broad Brush' => 'I/C',
            'Broomstick' => 'I',
            'Bruleur' => 'P',
            'Buckaroo' => 'B/I',
            'Buckpasser' => 'C',
            'Bull Dog' => 'B',
            'Bull Lea' => 'C',
            'Busted' => 'S',
            'Cape Cross' => 'C',
            'Caro' => 'I/C',
            'Carson City' => 'B/I',
            'Chateau Bouscaut' => 'P',
            'Chaucer' => 'S',
            "Chief's Crown" => 'I/S',
            'Cicero' => 'B',
            'Clarissimus' => 'C',
            'Codex' => 'I/C',
            'Colorado' => 'I',
            'Congreve' => 'I',
            'Count Fleet' => 'C',
            'Court Martial' => 'B',
            'Creme Dela Creme' => 'C/S',
            'Crepello' => 'P',
            'Damascus' => 'I/C',
            'Danzig' => 'I/C',
            'Dark Ronald' => 'P',
            'Darshaan' => 'S',
            'Discovery' => 'S',
            'Djebel' => 'I',
            'Donatello II' => 'P',
            'Double Jay' => 'B',
            'Dr. Fager' => 'I',
            'Dubawi' => 'I/S',
            'Eight Thirty' => 'I',
            'El Prado' => 'B/I',
            'Ela-Mana-Mou' => 'P',
            'Equipoise' => 'I/C',
            'Exclusive Native' => 'C',
            'Fair Play' => 'S/P',
            'Fair Trial' => 'B',
            'Fairway' => 'B',
            'Fappiano' => 'I/C',
            'Fasliyev' => 'B',
            'Forli' => 'C',
            'Foxbridge' => 'P',
            'Full Sail' => 'I',
            'Gainsborough' => 'C',
            'Galileo' => 'C/S',
            'Gallant Man' => 'B/I',
            "Giant's Causeway" => 'C',
            'Gone West' => 'I/C',
            'Graustark' => 'C/S',
            'Grey Dawn II' => 'B/I',
            'Grey Sovereign' => 'B',
            'Gundomar' => 'C',
            'Habitat' => 'B',
            'Hail to Reason' => 'C',
            'Halo' => 'B/C',
            'Havresac II' => 'I',
            'Heliopolis' => 'B',
            'Herbager' => 'C/S',
            'High Top' => 'C',
            'His Majesty' => 'C',
            'Hoist the Flag' => 'B/I',
            'Hurry On' => 'P',
            'Hyperion' => 'B/C',
            'Icecapade' => 'B/C',
            'In Reality' => 'B/C',
            'In the Wings' => 'C/S',
            'Indian Ridge' => 'I',
            'Intentionally' => 'B/I',
            'Key to the Mint' => 'B/C',
            'Khaled' => 'I',
            'King Salmon' => 'I',
            'Kingmambo' => 'C/S',
            "King's Bishop" => 'B/I',
            'La Farina' => 'P',
            'Le Fabuleux' => 'P',
            'Linamix' => 'C/S',
            'Lost Code' => 'B/I',
            'Luthier' => 'C',
            'Lyphard' => 'C',
            'Mahmoud' => 'I/C',
            "Man o' War" => 'S',
            'Massine' => 'P',
            'Midstream' => 'C',
            'Mieuxce' => 'P',
            'Mill Reef' => 'C/S',
            'Monsun' => 'C/S',
            'Montjeu' => 'C/S',
            'Mossborough' => 'C',
            'Mr. Prospector' => 'B/C',
            'My Babu' => 'B',
            'Nashua' => 'I/C',
            'Nasrullah' => 'B',
            'Native Dancer' => 'I/C',
            'Navarro' => 'C',
            'Nearco' => 'B/C',
            'Never Bend' => 'B/I',
            'Never Say Die' => 'C',
            'Nijinsky II' => 'C/S',
            'Niniski' => 'C/P',
            'Nodouble' => 'C/P',
            'Noholme II' => 'B/C',
            'Northern Dancer' => 'B/C',
            'Nureyev' => 'C',
            'Oleander' => 'S',
            'Olympia' => 'B',
            'Orby' => 'B',
            'Ortello' => 'P',
            'Panorama' => 'B',
            'Persian Gulf' => 'C',
            'Peter Pan' => 'B',
            'Petition' => 'I',
            'Phalaris' => 'B',
            'Pharis II' => 'B',
            'Pharos' => 'I',
            'Pia Star' => 'S',
            'Pilate' => 'C',
            'Pivotal' => 'I/C',
            'Pleasant Colony' => 'I',
            'Polynesian' => 'I',
            'Pompey' => 'B',
            'Precipitation' => 'P',
            'Pretense' => 'C',
            'Prince Bio' => 'C',
            'Prince Chevalier' => 'C',
            'Prince John' => 'C',
            'Prince Rose' => 'C',
            'Princequillo' => 'I/S',
            'Promised Land' => 'C',
            'Pulpit' => 'I/C',
            'Rabelais' => 'P',
            'Rainbow Quest' => 'C/S',
            'Raise a Native' => 'B',
            'Reliance II' => 'S/P',
            'Relko' => 'S',
            'Reviewer' => 'B/C',
            'Ribot' => 'C/P',
            'Right Royal' => 'S',
            'Riverman' => 'I/C',
            'Roberto' => 'C',
            'Rock Sand' => 'C/S',
            'Roman' => 'B/I',
            "Rough'n Tumble" => 'B/C',
            'Round Table' => 'S',
            'Royal Academy' => 'B/I',
            'Royal Charger' => 'B',
            'Run the Gantlet' => 'P',
            "Sadler's Wells" => 'C/S',
            'Sardanapale' => 'P',
            'Sea-Bird' => 'S',
            'Seattle Slew' => 'B/C',
            'Secretariat' => 'I/C',
            'Shamardal' => 'I/C',
            'Sharpen Up' => 'B/C',
            'Shirley Heights' => 'C/P',
            'Sicambre' => 'C',
            'Sideral' => 'C',
            'Sir Cosmo' => 'B',
            'Sir Gallahad III' => 'C',
            'Sir Gaylord' => 'I/C',
            'Sir Ivor' => 'I/C',
            'Smart Strike' => 'I/C',
            'Solario' => 'P',
            'Son-in-Law' => 'P',
            'Speak John' => 'B/I',
            'Spearmint' => 'P',
            'Spy Song' => 'B',
            'Stage Door Johnny' => 'S/P',
            'Star Kingdom' => 'I/C',
            'Star Shoot' => 'I',
            'Sunny Boy' => 'P',
            'Sunstar' => 'S',
            'Sweep' => 'I',
            'Swynford' => 'C',
            'T.V. Lark' => 'I',
            'Tantieme' => 'S',
            'Teddy' => 'S',
            'The Tetrarch' => 'I',
            'Ticino' => 'C/S',
            'Tom Fool' => 'I/C',
            'Tom Rolfe' => 'C/P',
            'Tourbillon' => 'C/P',
            'Tracery' => 'C',
            'Traghetto' => 'I',
            'Tudor Minstrel' => 'B',
            'Turn-to' => 'B/I',
            'Ultimus' => 'B',
            'Unbridled' => 'B/I',
            "Unbridled's Song" => 'I',
            'Vaguely Noble' => 'C/P',
            'Vandale' => 'P',
            'Vatellor' => 'P',
            'Vatout' => 'S',
            'Vieux Manoir' => 'C',
            'War Admiral' => 'C',
            'What a Pleasure' => 'B',
            'Wild Risk' => 'P',
            'Worden' => 'S',
        ];

        // Later international additions / revisions (chef-de-race.com.au complete list).
        $international_additions = [
            'Alleged' => 'C/P',
            'Arch' => 'C',
            "Bolt d'Oro" => 'B/C',
            'Candy Ride' => 'B/C',
            'Constitution' => 'B/C',
            'Cozzene' => 'C/S',
            'Curlin' => 'C',
            'Distorted Humor' => 'I/C',
            'Dynaformer' => 'C',
            'Elusive Quality' => 'B/C',
            'Empire Maker' => 'C/S',
            'English Channel' => 'S/P',
            'Forestry' => 'B/I',
            'Great Above' => 'B/C',
            'Gun Runner' => 'B/C',
            'Holy Bull' => 'I/C',
            'In Excess' => 'B/I',
            'Into Mischief' => 'B/C',
            'Kantharos' => 'B/I',
            "Kitten's Joy" => 'C',
            "Liam's Map" => 'C',
            'Lord Avie' => 'C',
            "Maclean's Music" => 'B',
            "Medaglia d'Oro" => 'C',
            'More Than Ready' => 'B/C',
            'Munnings' => 'B/I',
            'Not This Time' => 'B/C',
            'Practical Joke' => 'B/I',
            'Quality Road' => 'I/C',
            'Quiet American' => 'C',
            'Rubiano' => 'B/I',
            'Scat Daddy' => 'I/C',
            'Slewpy' => 'B/I',
            'Speightstown' => 'B/I',
            'Street Cry' => 'I/C',
            'Street Sense' => 'B/C',
            'Tapit' => 'C',
            'Thunder Gulch' => 'C',
            'Tiznow' => 'I/C',
            'Twirling Candy' => 'B/I',
            "Unbridled's Song" => 'B/C',
            'Uncle Mo' => 'I/C',
            'Violence' => 'B',
        ];

        return array_merge($bloodhorse_2019, $international_additions);
    }
}
